// Code generated by go-swagger; DO NOT EDIT.

package fav_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// NewFavoriteARecipeParams creates a new FavoriteARecipeParams object
// with the default values initialized.
func NewFavoriteARecipeParams() *FavoriteARecipeParams {
	var ()
	return &FavoriteARecipeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFavoriteARecipeParamsWithTimeout creates a new FavoriteARecipeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFavoriteARecipeParamsWithTimeout(timeout time.Duration) *FavoriteARecipeParams {
	var ()
	return &FavoriteARecipeParams{

		timeout: timeout,
	}
}

// NewFavoriteARecipeParamsWithContext creates a new FavoriteARecipeParams object
// with the default values initialized, and the ability to set a context for a request
func NewFavoriteARecipeParamsWithContext(ctx context.Context) *FavoriteARecipeParams {
	var ()
	return &FavoriteARecipeParams{

		Context: ctx,
	}
}

// NewFavoriteARecipeParamsWithHTTPClient creates a new FavoriteARecipeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFavoriteARecipeParamsWithHTTPClient(client *http.Client) *FavoriteARecipeParams {
	var ()
	return &FavoriteARecipeParams{
		HTTPClient: client,
	}
}

/*FavoriteARecipeParams contains all the parameters to send to the API endpoint
for the favorite a recipe operation typically these are written to a http.Request
*/
type FavoriteARecipeParams struct {

	/*JSONBody
	  The recipe information (either the recipe's url or the recipeId from the cheerychow DB) you want to favourite..

	*/
	JSONBody *models.FavRecipe

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the favorite a recipe params
func (o *FavoriteARecipeParams) WithTimeout(timeout time.Duration) *FavoriteARecipeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the favorite a recipe params
func (o *FavoriteARecipeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the favorite a recipe params
func (o *FavoriteARecipeParams) WithContext(ctx context.Context) *FavoriteARecipeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the favorite a recipe params
func (o *FavoriteARecipeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the favorite a recipe params
func (o *FavoriteARecipeParams) WithHTTPClient(client *http.Client) *FavoriteARecipeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the favorite a recipe params
func (o *FavoriteARecipeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the favorite a recipe params
func (o *FavoriteARecipeParams) WithJSONBody(jSONBody *models.FavRecipe) *FavoriteARecipeParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the favorite a recipe params
func (o *FavoriteARecipeParams) SetJSONBody(jSONBody *models.FavRecipe) {
	o.JSONBody = jSONBody
}

// WriteToRequest writes these params to a swagger request
func (o *FavoriteARecipeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
