// Code generated by go-swagger; DO NOT EDIT.

package fav_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// FavoriteRecipesReader is a Reader for the FavoriteRecipes structure.
type FavoriteRecipesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FavoriteRecipesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFavoriteRecipesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewFavoriteRecipesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFavoriteRecipesOK creates a FavoriteRecipesOK with default headers values
func NewFavoriteRecipesOK() *FavoriteRecipesOK {
	return &FavoriteRecipesOK{}
}

/*FavoriteRecipesOK handles this case with default header values.

Description was not specified
*/
type FavoriteRecipesOK struct {
	Payload []*models.FavRecipe
}

func (o *FavoriteRecipesOK) Error() string {
	return fmt.Sprintf("[GET /fav-recipe][%d] favoriteRecipesOK  %+v", 200, o.Payload)
}

func (o *FavoriteRecipesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFavoriteRecipesBadRequest creates a FavoriteRecipesBadRequest with default headers values
func NewFavoriteRecipesBadRequest() *FavoriteRecipesBadRequest {
	return &FavoriteRecipesBadRequest{}
}

/*FavoriteRecipesBadRequest handles this case with default header values.

Description was not specified
*/
type FavoriteRecipesBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *FavoriteRecipesBadRequest) Error() string {
	return fmt.Sprintf("[GET /fav-recipe][%d] favoriteRecipesBadRequest  %+v", 400, o.Payload)
}

func (o *FavoriteRecipesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
