// Code generated by go-swagger; DO NOT EDIT.

package rate_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/go-client/models"
)

// GetMyRecipeRatingByURLReader is a Reader for the GetMyRecipeRatingByURL structure.
type GetMyRecipeRatingByURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMyRecipeRatingByURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMyRecipeRatingByURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetMyRecipeRatingByURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetMyRecipeRatingByURLNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMyRecipeRatingByURLOK creates a GetMyRecipeRatingByURLOK with default headers values
func NewGetMyRecipeRatingByURLOK() *GetMyRecipeRatingByURLOK {
	return &GetMyRecipeRatingByURLOK{}
}

/*GetMyRecipeRatingByURLOK handles this case with default header values.

Description was not specified
*/
type GetMyRecipeRatingByURLOK struct {
	Payload *models.RecipeRating
}

func (o *GetMyRecipeRatingByURLOK) Error() string {
	return fmt.Sprintf("[GET /rate-recipe/my-rating-by-url/{url}][%d] getMyRecipeRatingByUrlOK  %+v", 200, o.Payload)
}

func (o *GetMyRecipeRatingByURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RecipeRating)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMyRecipeRatingByURLBadRequest creates a GetMyRecipeRatingByURLBadRequest with default headers values
func NewGetMyRecipeRatingByURLBadRequest() *GetMyRecipeRatingByURLBadRequest {
	return &GetMyRecipeRatingByURLBadRequest{}
}

/*GetMyRecipeRatingByURLBadRequest handles this case with default header values.

Description was not specified
*/
type GetMyRecipeRatingByURLBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *GetMyRecipeRatingByURLBadRequest) Error() string {
	return fmt.Sprintf("[GET /rate-recipe/my-rating-by-url/{url}][%d] getMyRecipeRatingByUrlBadRequest  %+v", 400, o.Payload)
}

func (o *GetMyRecipeRatingByURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMyRecipeRatingByURLNotFound creates a GetMyRecipeRatingByURLNotFound with default headers values
func NewGetMyRecipeRatingByURLNotFound() *GetMyRecipeRatingByURLNotFound {
	return &GetMyRecipeRatingByURLNotFound{}
}

/*GetMyRecipeRatingByURLNotFound handles this case with default header values.

Recipe not found
*/
type GetMyRecipeRatingByURLNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *GetMyRecipeRatingByURLNotFound) Error() string {
	return fmt.Sprintf("[GET /rate-recipe/my-rating-by-url/{url}][%d] getMyRecipeRatingByUrlNotFound  %+v", 404, o.Payload)
}

func (o *GetMyRecipeRatingByURLNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
