// Code generated by go-swagger; DO NOT EDIT.

package rate_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMyRecipeRatingByURLParams creates a new GetMyRecipeRatingByURLParams object
// with the default values initialized.
func NewGetMyRecipeRatingByURLParams() *GetMyRecipeRatingByURLParams {
	var ()
	return &GetMyRecipeRatingByURLParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMyRecipeRatingByURLParamsWithTimeout creates a new GetMyRecipeRatingByURLParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMyRecipeRatingByURLParamsWithTimeout(timeout time.Duration) *GetMyRecipeRatingByURLParams {
	var ()
	return &GetMyRecipeRatingByURLParams{

		timeout: timeout,
	}
}

// NewGetMyRecipeRatingByURLParamsWithContext creates a new GetMyRecipeRatingByURLParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMyRecipeRatingByURLParamsWithContext(ctx context.Context) *GetMyRecipeRatingByURLParams {
	var ()
	return &GetMyRecipeRatingByURLParams{

		Context: ctx,
	}
}

// NewGetMyRecipeRatingByURLParamsWithHTTPClient creates a new GetMyRecipeRatingByURLParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMyRecipeRatingByURLParamsWithHTTPClient(client *http.Client) *GetMyRecipeRatingByURLParams {
	var ()
	return &GetMyRecipeRatingByURLParams{
		HTTPClient: client,
	}
}

/*GetMyRecipeRatingByURLParams contains all the parameters to send to the API endpoint
for the get my recipe rating by Url operation typically these are written to a http.Request
*/
type GetMyRecipeRatingByURLParams struct {

	/*URL
	  The url of the recipe, if it's already in the database.

	*/
	URL string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) WithTimeout(timeout time.Duration) *GetMyRecipeRatingByURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) WithContext(ctx context.Context) *GetMyRecipeRatingByURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) WithHTTPClient(client *http.Client) *GetMyRecipeRatingByURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithURL adds the url to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) WithURL(url string) *GetMyRecipeRatingByURLParams {
	o.SetURL(url)
	return o
}

// SetURL adds the url to the get my recipe rating by Url params
func (o *GetMyRecipeRatingByURLParams) SetURL(url string) {
	o.URL = url
}

// WriteToRequest writes these params to a swagger request
func (o *GetMyRecipeRatingByURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param url
	if err := r.SetPathParam("url", o.URL); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
