// Code generated by go-swagger; DO NOT EDIT.

package food

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFoodWeightNamesParams creates a new FoodWeightNamesParams object
// with the default values initialized.
func NewFoodWeightNamesParams() *FoodWeightNamesParams {
	var ()
	return &FoodWeightNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFoodWeightNamesParamsWithTimeout creates a new FoodWeightNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFoodWeightNamesParamsWithTimeout(timeout time.Duration) *FoodWeightNamesParams {
	var ()
	return &FoodWeightNamesParams{

		timeout: timeout,
	}
}

// NewFoodWeightNamesParamsWithContext creates a new FoodWeightNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewFoodWeightNamesParamsWithContext(ctx context.Context) *FoodWeightNamesParams {
	var ()
	return &FoodWeightNamesParams{

		Context: ctx,
	}
}

// NewFoodWeightNamesParamsWithHTTPClient creates a new FoodWeightNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFoodWeightNamesParamsWithHTTPClient(client *http.Client) *FoodWeightNamesParams {
	var ()
	return &FoodWeightNamesParams{
		HTTPClient: client,
	}
}

/*FoodWeightNamesParams contains all the parameters to send to the API endpoint
for the food weight names operation typically these are written to a http.Request
*/
type FoodWeightNamesParams struct {

	/*FoodID
	  Food id which you want a list of known foods weights for

	*/
	FoodID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the food weight names params
func (o *FoodWeightNamesParams) WithTimeout(timeout time.Duration) *FoodWeightNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the food weight names params
func (o *FoodWeightNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the food weight names params
func (o *FoodWeightNamesParams) WithContext(ctx context.Context) *FoodWeightNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the food weight names params
func (o *FoodWeightNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the food weight names params
func (o *FoodWeightNamesParams) WithHTTPClient(client *http.Client) *FoodWeightNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the food weight names params
func (o *FoodWeightNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFoodID adds the foodID to the food weight names params
func (o *FoodWeightNamesParams) WithFoodID(foodID int32) *FoodWeightNamesParams {
	o.SetFoodID(foodID)
	return o
}

// SetFoodID adds the foodId to the food weight names params
func (o *FoodWeightNamesParams) SetFoodID(foodID int32) {
	o.FoodID = foodID
}

// WriteToRequest writes these params to a swagger request
func (o *FoodWeightNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param foodId
	if err := r.SetPathParam("foodId", swag.FormatInt32(o.FoodID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
