// Code generated by go-swagger; DO NOT EDIT.

package food

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// ListFoodGroupsReader is a Reader for the ListFoodGroups structure.
type ListFoodGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListFoodGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListFoodGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewListFoodGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListFoodGroupsOK creates a ListFoodGroupsOK with default headers values
func NewListFoodGroupsOK() *ListFoodGroupsOK {
	return &ListFoodGroupsOK{}
}

/*ListFoodGroupsOK handles this case with default header values.

Description was not specified
*/
type ListFoodGroupsOK struct {
	Payload []*models.FoodGroup
}

func (o *ListFoodGroupsOK) Error() string {
	return fmt.Sprintf("[GET /food/groups][%d] listFoodGroupsOK  %+v", 200, o.Payload)
}

func (o *ListFoodGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListFoodGroupsBadRequest creates a ListFoodGroupsBadRequest with default headers values
func NewListFoodGroupsBadRequest() *ListFoodGroupsBadRequest {
	return &ListFoodGroupsBadRequest{}
}

/*ListFoodGroupsBadRequest handles this case with default header values.

Description was not specified
*/
type ListFoodGroupsBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *ListFoodGroupsBadRequest) Error() string {
	return fmt.Sprintf("[GET /food/groups][%d] listFoodGroupsBadRequest  %+v", 400, o.Payload)
}

func (o *ListFoodGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
