// Code generated by go-swagger; DO NOT EDIT.

package food

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchAvailableIngredientParams creates a new SearchAvailableIngredientParams object
// with the default values initialized.
func NewSearchAvailableIngredientParams() *SearchAvailableIngredientParams {
	var (
		limitDefault = int32(1000)
	)
	return &SearchAvailableIngredientParams{
		Limit: &limitDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchAvailableIngredientParamsWithTimeout creates a new SearchAvailableIngredientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchAvailableIngredientParamsWithTimeout(timeout time.Duration) *SearchAvailableIngredientParams {
	var (
		limitDefault = int32(1000)
	)
	return &SearchAvailableIngredientParams{
		Limit: &limitDefault,

		timeout: timeout,
	}
}

// NewSearchAvailableIngredientParamsWithContext creates a new SearchAvailableIngredientParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchAvailableIngredientParamsWithContext(ctx context.Context) *SearchAvailableIngredientParams {
	var (
		limitDefault = int32(1000)
	)
	return &SearchAvailableIngredientParams{
		Limit: &limitDefault,

		Context: ctx,
	}
}

// NewSearchAvailableIngredientParamsWithHTTPClient creates a new SearchAvailableIngredientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchAvailableIngredientParamsWithHTTPClient(client *http.Client) *SearchAvailableIngredientParams {
	var (
		limitDefault = int32(1000)
	)
	return &SearchAvailableIngredientParams{
		Limit:      &limitDefault,
		HTTPClient: client,
	}
}

/*SearchAvailableIngredientParams contains all the parameters to send to the API endpoint
for the search available ingredient operation typically these are written to a http.Request
*/
type SearchAvailableIngredientParams struct {

	/*Limit
	  Limit the number of results returned.

	*/
	Limit *int32
	/*Offset
	  The offset into search results.

	*/
	Offset *int64
	/*SearchTerm
	  The search term to use when searching through ingredient names

	*/
	SearchTerm *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithTimeout(timeout time.Duration) *SearchAvailableIngredientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithContext(ctx context.Context) *SearchAvailableIngredientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithHTTPClient(client *http.Client) *SearchAvailableIngredientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithLimit(limit *int32) *SearchAvailableIngredientParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithOffset(offset *int64) *SearchAvailableIngredientParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSearchTerm adds the searchTerm to the search available ingredient params
func (o *SearchAvailableIngredientParams) WithSearchTerm(searchTerm *string) *SearchAvailableIngredientParams {
	o.SetSearchTerm(searchTerm)
	return o
}

// SetSearchTerm adds the searchTerm to the search available ingredient params
func (o *SearchAvailableIngredientParams) SetSearchTerm(searchTerm *string) {
	o.SearchTerm = searchTerm
}

// WriteToRequest writes these params to a swagger request
func (o *SearchAvailableIngredientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.SearchTerm != nil {

		// query param search-term
		var qrSearchTerm string
		if o.SearchTerm != nil {
			qrSearchTerm = *o.SearchTerm
		}
		qSearchTerm := qrSearchTerm
		if qSearchTerm != "" {
			if err := r.SetQueryParam("search-term", qSearchTerm); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
