// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCopyRecipeExactlyParams creates a new CopyRecipeExactlyParams object
// with the default values initialized.
func NewCopyRecipeExactlyParams() *CopyRecipeExactlyParams {
	var ()
	return &CopyRecipeExactlyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCopyRecipeExactlyParamsWithTimeout creates a new CopyRecipeExactlyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCopyRecipeExactlyParamsWithTimeout(timeout time.Duration) *CopyRecipeExactlyParams {
	var ()
	return &CopyRecipeExactlyParams{

		timeout: timeout,
	}
}

// NewCopyRecipeExactlyParamsWithContext creates a new CopyRecipeExactlyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCopyRecipeExactlyParamsWithContext(ctx context.Context) *CopyRecipeExactlyParams {
	var ()
	return &CopyRecipeExactlyParams{

		Context: ctx,
	}
}

// NewCopyRecipeExactlyParamsWithHTTPClient creates a new CopyRecipeExactlyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCopyRecipeExactlyParamsWithHTTPClient(client *http.Client) *CopyRecipeExactlyParams {
	var ()
	return &CopyRecipeExactlyParams{
		HTTPClient: client,
	}
}

/*CopyRecipeExactlyParams contains all the parameters to send to the API endpoint
for the copy recipe exactly operation typically these are written to a http.Request
*/
type CopyRecipeExactlyParams struct {

	/*RecipeID
	  The recipe you want to make changes to

	*/
	RecipeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) WithTimeout(timeout time.Duration) *CopyRecipeExactlyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) WithContext(ctx context.Context) *CopyRecipeExactlyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) WithHTTPClient(client *http.Client) *CopyRecipeExactlyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecipeID adds the recipeID to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) WithRecipeID(recipeID string) *CopyRecipeExactlyParams {
	o.SetRecipeID(recipeID)
	return o
}

// SetRecipeID adds the recipeId to the copy recipe exactly params
func (o *CopyRecipeExactlyParams) SetRecipeID(recipeID string) {
	o.RecipeID = recipeID
}

// WriteToRequest writes these params to a swagger request
func (o *CopyRecipeExactlyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recipeId
	if err := r.SetPathParam("recipeId", o.RecipeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
