// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// NewCopyRecipeToMyRecipesWithChangesParams creates a new CopyRecipeToMyRecipesWithChangesParams object
// with the default values initialized.
func NewCopyRecipeToMyRecipesWithChangesParams() *CopyRecipeToMyRecipesWithChangesParams {
	var ()
	return &CopyRecipeToMyRecipesWithChangesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCopyRecipeToMyRecipesWithChangesParamsWithTimeout creates a new CopyRecipeToMyRecipesWithChangesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCopyRecipeToMyRecipesWithChangesParamsWithTimeout(timeout time.Duration) *CopyRecipeToMyRecipesWithChangesParams {
	var ()
	return &CopyRecipeToMyRecipesWithChangesParams{

		timeout: timeout,
	}
}

// NewCopyRecipeToMyRecipesWithChangesParamsWithContext creates a new CopyRecipeToMyRecipesWithChangesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCopyRecipeToMyRecipesWithChangesParamsWithContext(ctx context.Context) *CopyRecipeToMyRecipesWithChangesParams {
	var ()
	return &CopyRecipeToMyRecipesWithChangesParams{

		Context: ctx,
	}
}

// NewCopyRecipeToMyRecipesWithChangesParamsWithHTTPClient creates a new CopyRecipeToMyRecipesWithChangesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCopyRecipeToMyRecipesWithChangesParamsWithHTTPClient(client *http.Client) *CopyRecipeToMyRecipesWithChangesParams {
	var ()
	return &CopyRecipeToMyRecipesWithChangesParams{
		HTTPClient: client,
	}
}

/*CopyRecipeToMyRecipesWithChangesParams contains all the parameters to send to the API endpoint
for the copy recipe to my recipes with changes operation typically these are written to a http.Request
*/
type CopyRecipeToMyRecipesWithChangesParams struct {

	/*JSONBody
	  The recipe object with changes you want to make to the original recipe.

	*/
	JSONBody *models.Recipe
	/*RecipeID
	  The recipe you want to make changes to

	*/
	RecipeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) WithTimeout(timeout time.Duration) *CopyRecipeToMyRecipesWithChangesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) WithContext(ctx context.Context) *CopyRecipeToMyRecipesWithChangesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) WithHTTPClient(client *http.Client) *CopyRecipeToMyRecipesWithChangesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) WithJSONBody(jSONBody *models.Recipe) *CopyRecipeToMyRecipesWithChangesParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) SetJSONBody(jSONBody *models.Recipe) {
	o.JSONBody = jSONBody
}

// WithRecipeID adds the recipeID to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) WithRecipeID(recipeID string) *CopyRecipeToMyRecipesWithChangesParams {
	o.SetRecipeID(recipeID)
	return o
}

// SetRecipeID adds the recipeId to the copy recipe to my recipes with changes params
func (o *CopyRecipeToMyRecipesWithChangesParams) SetRecipeID(recipeID string) {
	o.RecipeID = recipeID
}

// WriteToRequest writes these params to a swagger request
func (o *CopyRecipeToMyRecipesWithChangesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	// path param recipeId
	if err := r.SetPathParam("recipeId", o.RecipeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
