// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMyRecipesParams creates a new GetMyRecipesParams object
// with the default values initialized.
func NewGetMyRecipesParams() *GetMyRecipesParams {
	var (
		includeCommonNamesDefault         = bool(false)
		includeFoodIDDefault              = bool(false)
		includeFoodNamesDefault           = bool(false)
		includeGdaDefault                 = bool(false)
		includeNutritionDefault           = bool(false)
		includeNutritionPerPortionDefault = bool(false)
		includeNutritionTipsDefault       = bool(false)
		includeRecipeCategoriesDefault    = bool(false)
	)
	return &GetMyRecipesParams{
		IncludeCommonNames:         &includeCommonNamesDefault,
		IncludeFoodID:              &includeFoodIDDefault,
		IncludeFoodNames:           &includeFoodNamesDefault,
		IncludeGda:                 &includeGdaDefault,
		IncludeNutrition:           &includeNutritionDefault,
		IncludeNutritionPerPortion: &includeNutritionPerPortionDefault,
		IncludeNutritionTips:       &includeNutritionTipsDefault,
		IncludeRecipeCategories:    &includeRecipeCategoriesDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMyRecipesParamsWithTimeout creates a new GetMyRecipesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMyRecipesParamsWithTimeout(timeout time.Duration) *GetMyRecipesParams {
	var (
		includeCommonNamesDefault         = bool(false)
		includeFoodIDDefault              = bool(false)
		includeFoodNamesDefault           = bool(false)
		includeGdaDefault                 = bool(false)
		includeNutritionDefault           = bool(false)
		includeNutritionPerPortionDefault = bool(false)
		includeNutritionTipsDefault       = bool(false)
		includeRecipeCategoriesDefault    = bool(false)
	)
	return &GetMyRecipesParams{
		IncludeCommonNames:         &includeCommonNamesDefault,
		IncludeFoodID:              &includeFoodIDDefault,
		IncludeFoodNames:           &includeFoodNamesDefault,
		IncludeGda:                 &includeGdaDefault,
		IncludeNutrition:           &includeNutritionDefault,
		IncludeNutritionPerPortion: &includeNutritionPerPortionDefault,
		IncludeNutritionTips:       &includeNutritionTipsDefault,
		IncludeRecipeCategories:    &includeRecipeCategoriesDefault,

		timeout: timeout,
	}
}

// NewGetMyRecipesParamsWithContext creates a new GetMyRecipesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMyRecipesParamsWithContext(ctx context.Context) *GetMyRecipesParams {
	var (
		includeCommonNamesDefault         = bool(false)
		includeFoodIdDefault              = bool(false)
		includeFoodNamesDefault           = bool(false)
		includeGdaDefault                 = bool(false)
		includeNutritionDefault           = bool(false)
		includeNutritionPerPortionDefault = bool(false)
		includeNutritionTipsDefault       = bool(false)
		includeRecipeCategoriesDefault    = bool(false)
	)
	return &GetMyRecipesParams{
		IncludeCommonNames:         &includeCommonNamesDefault,
		IncludeFoodID:              &includeFoodIdDefault,
		IncludeFoodNames:           &includeFoodNamesDefault,
		IncludeGda:                 &includeGdaDefault,
		IncludeNutrition:           &includeNutritionDefault,
		IncludeNutritionPerPortion: &includeNutritionPerPortionDefault,
		IncludeNutritionTips:       &includeNutritionTipsDefault,
		IncludeRecipeCategories:    &includeRecipeCategoriesDefault,

		Context: ctx,
	}
}

// NewGetMyRecipesParamsWithHTTPClient creates a new GetMyRecipesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMyRecipesParamsWithHTTPClient(client *http.Client) *GetMyRecipesParams {
	var (
		includeCommonNamesDefault         = bool(false)
		includeFoodIdDefault              = bool(false)
		includeFoodNamesDefault           = bool(false)
		includeGdaDefault                 = bool(false)
		includeNutritionDefault           = bool(false)
		includeNutritionPerPortionDefault = bool(false)
		includeNutritionTipsDefault       = bool(false)
		includeRecipeCategoriesDefault    = bool(false)
	)
	return &GetMyRecipesParams{
		IncludeCommonNames:         &includeCommonNamesDefault,
		IncludeFoodID:              &includeFoodIdDefault,
		IncludeFoodNames:           &includeFoodNamesDefault,
		IncludeGda:                 &includeGdaDefault,
		IncludeNutrition:           &includeNutritionDefault,
		IncludeNutritionPerPortion: &includeNutritionPerPortionDefault,
		IncludeNutritionTips:       &includeNutritionTipsDefault,
		IncludeRecipeCategories:    &includeRecipeCategoriesDefault,
		HTTPClient:                 client,
	}
}

/*GetMyRecipesParams contains all the parameters to send to the API endpoint
for the get my recipes operation typically these are written to a http.Request
*/
type GetMyRecipesParams struct {

	/*IncludeCommonNames
	  Should the recipe's ingredient common names be included?

	*/
	IncludeCommonNames *bool
	/*IncludeFoodID
	  Should the recipe's ingredient food id's be included? This can be useful if you need the names of foods as a map, where the key is the food id, the value the food name.

	*/
	IncludeFoodID *bool
	/*IncludeFoodNames
	  Should the recipe's ingredient food names be included (this is different from the common names since the storage is a map, where key is the foodId and value is the ingredient common name)

	*/
	IncludeFoodNames *bool
	/*IncludeGda
	  Should the general daily provision for the recipe be included?

	*/
	IncludeGda *bool
	/*IncludeNutrition
	  Should the recipe's nutrition field be populated?

	*/
	IncludeNutrition *bool
	/*IncludeNutritionPerPortion
	  Should the recipe's nutrition per portion be included?

	*/
	IncludeNutritionPerPortion *bool
	/*IncludeNutritionTips
	  Provide tips and information regarding the nutritional content for this recipe.

	*/
	IncludeNutritionTips *bool
	/*IncludeRecipeCategories
	  Should the recipe's categories be included? The Recipe categories include; vegan-friendly, vegetarion, pescatarian, gluten-free, low-fat, low-sat-fat, low-sugar.

	*/
	IncludeRecipeCategories *bool
	/*Limit
	  Limit the number of results returned.

	*/
	Limit *int32
	/*Offset
	  The offset into search results.

	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get my recipes params
func (o *GetMyRecipesParams) WithTimeout(timeout time.Duration) *GetMyRecipesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get my recipes params
func (o *GetMyRecipesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get my recipes params
func (o *GetMyRecipesParams) WithContext(ctx context.Context) *GetMyRecipesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get my recipes params
func (o *GetMyRecipesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get my recipes params
func (o *GetMyRecipesParams) WithHTTPClient(client *http.Client) *GetMyRecipesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get my recipes params
func (o *GetMyRecipesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeCommonNames adds the includeCommonNames to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeCommonNames(includeCommonNames *bool) *GetMyRecipesParams {
	o.SetIncludeCommonNames(includeCommonNames)
	return o
}

// SetIncludeCommonNames adds the includeCommonNames to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeCommonNames(includeCommonNames *bool) {
	o.IncludeCommonNames = includeCommonNames
}

// WithIncludeFoodID adds the includeFoodID to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeFoodID(includeFoodID *bool) *GetMyRecipesParams {
	o.SetIncludeFoodID(includeFoodID)
	return o
}

// SetIncludeFoodID adds the includeFoodId to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeFoodID(includeFoodID *bool) {
	o.IncludeFoodID = includeFoodID
}

// WithIncludeFoodNames adds the includeFoodNames to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeFoodNames(includeFoodNames *bool) *GetMyRecipesParams {
	o.SetIncludeFoodNames(includeFoodNames)
	return o
}

// SetIncludeFoodNames adds the includeFoodNames to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeFoodNames(includeFoodNames *bool) {
	o.IncludeFoodNames = includeFoodNames
}

// WithIncludeGda adds the includeGda to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeGda(includeGda *bool) *GetMyRecipesParams {
	o.SetIncludeGda(includeGda)
	return o
}

// SetIncludeGda adds the includeGda to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeGda(includeGda *bool) {
	o.IncludeGda = includeGda
}

// WithIncludeNutrition adds the includeNutrition to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeNutrition(includeNutrition *bool) *GetMyRecipesParams {
	o.SetIncludeNutrition(includeNutrition)
	return o
}

// SetIncludeNutrition adds the includeNutrition to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeNutrition(includeNutrition *bool) {
	o.IncludeNutrition = includeNutrition
}

// WithIncludeNutritionPerPortion adds the includeNutritionPerPortion to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeNutritionPerPortion(includeNutritionPerPortion *bool) *GetMyRecipesParams {
	o.SetIncludeNutritionPerPortion(includeNutritionPerPortion)
	return o
}

// SetIncludeNutritionPerPortion adds the includeNutritionPerPortion to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeNutritionPerPortion(includeNutritionPerPortion *bool) {
	o.IncludeNutritionPerPortion = includeNutritionPerPortion
}

// WithIncludeNutritionTips adds the includeNutritionTips to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeNutritionTips(includeNutritionTips *bool) *GetMyRecipesParams {
	o.SetIncludeNutritionTips(includeNutritionTips)
	return o
}

// SetIncludeNutritionTips adds the includeNutritionTips to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeNutritionTips(includeNutritionTips *bool) {
	o.IncludeNutritionTips = includeNutritionTips
}

// WithIncludeRecipeCategories adds the includeRecipeCategories to the get my recipes params
func (o *GetMyRecipesParams) WithIncludeRecipeCategories(includeRecipeCategories *bool) *GetMyRecipesParams {
	o.SetIncludeRecipeCategories(includeRecipeCategories)
	return o
}

// SetIncludeRecipeCategories adds the includeRecipeCategories to the get my recipes params
func (o *GetMyRecipesParams) SetIncludeRecipeCategories(includeRecipeCategories *bool) {
	o.IncludeRecipeCategories = includeRecipeCategories
}

// WithLimit adds the limit to the get my recipes params
func (o *GetMyRecipesParams) WithLimit(limit *int32) *GetMyRecipesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get my recipes params
func (o *GetMyRecipesParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get my recipes params
func (o *GetMyRecipesParams) WithOffset(offset *int64) *GetMyRecipesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get my recipes params
func (o *GetMyRecipesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetMyRecipesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeCommonNames != nil {

		// query param include-common-names
		var qrIncludeCommonNames bool
		if o.IncludeCommonNames != nil {
			qrIncludeCommonNames = *o.IncludeCommonNames
		}
		qIncludeCommonNames := swag.FormatBool(qrIncludeCommonNames)
		if qIncludeCommonNames != "" {
			if err := r.SetQueryParam("include-common-names", qIncludeCommonNames); err != nil {
				return err
			}
		}

	}

	if o.IncludeFoodID != nil {

		// query param include-food-id
		var qrIncludeFoodID bool
		if o.IncludeFoodID != nil {
			qrIncludeFoodID = *o.IncludeFoodID
		}
		qIncludeFoodID := swag.FormatBool(qrIncludeFoodID)
		if qIncludeFoodID != "" {
			if err := r.SetQueryParam("include-food-id", qIncludeFoodID); err != nil {
				return err
			}
		}

	}

	if o.IncludeFoodNames != nil {

		// query param include-food-names
		var qrIncludeFoodNames bool
		if o.IncludeFoodNames != nil {
			qrIncludeFoodNames = *o.IncludeFoodNames
		}
		qIncludeFoodNames := swag.FormatBool(qrIncludeFoodNames)
		if qIncludeFoodNames != "" {
			if err := r.SetQueryParam("include-food-names", qIncludeFoodNames); err != nil {
				return err
			}
		}

	}

	if o.IncludeGda != nil {

		// query param include-gda
		var qrIncludeGda bool
		if o.IncludeGda != nil {
			qrIncludeGda = *o.IncludeGda
		}
		qIncludeGda := swag.FormatBool(qrIncludeGda)
		if qIncludeGda != "" {
			if err := r.SetQueryParam("include-gda", qIncludeGda); err != nil {
				return err
			}
		}

	}

	if o.IncludeNutrition != nil {

		// query param include-nutrition
		var qrIncludeNutrition bool
		if o.IncludeNutrition != nil {
			qrIncludeNutrition = *o.IncludeNutrition
		}
		qIncludeNutrition := swag.FormatBool(qrIncludeNutrition)
		if qIncludeNutrition != "" {
			if err := r.SetQueryParam("include-nutrition", qIncludeNutrition); err != nil {
				return err
			}
		}

	}

	if o.IncludeNutritionPerPortion != nil {

		// query param include-nutrition-per-portion
		var qrIncludeNutritionPerPortion bool
		if o.IncludeNutritionPerPortion != nil {
			qrIncludeNutritionPerPortion = *o.IncludeNutritionPerPortion
		}
		qIncludeNutritionPerPortion := swag.FormatBool(qrIncludeNutritionPerPortion)
		if qIncludeNutritionPerPortion != "" {
			if err := r.SetQueryParam("include-nutrition-per-portion", qIncludeNutritionPerPortion); err != nil {
				return err
			}
		}

	}

	if o.IncludeNutritionTips != nil {

		// query param include-nutrition-tips
		var qrIncludeNutritionTips bool
		if o.IncludeNutritionTips != nil {
			qrIncludeNutritionTips = *o.IncludeNutritionTips
		}
		qIncludeNutritionTips := swag.FormatBool(qrIncludeNutritionTips)
		if qIncludeNutritionTips != "" {
			if err := r.SetQueryParam("include-nutrition-tips", qIncludeNutritionTips); err != nil {
				return err
			}
		}

	}

	if o.IncludeRecipeCategories != nil {

		// query param include-recipe-categories
		var qrIncludeRecipeCategories bool
		if o.IncludeRecipeCategories != nil {
			qrIncludeRecipeCategories = *o.IncludeRecipeCategories
		}
		qIncludeRecipeCategories := swag.FormatBool(qrIncludeRecipeCategories)
		if qIncludeRecipeCategories != "" {
			if err := r.SetQueryParam("include-recipe-categories", qIncludeRecipeCategories); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
