// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetNutritionLabelJsReader is a Reader for the GetNutritionLabelJs structure.
type GetNutritionLabelJsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNutritionLabelJsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNutritionLabelJsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetNutritionLabelJsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetNutritionLabelJsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNutritionLabelJsOK creates a GetNutritionLabelJsOK with default headers values
func NewGetNutritionLabelJsOK() *GetNutritionLabelJsOK {
	return &GetNutritionLabelJsOK{}
}

/*GetNutritionLabelJsOK handles this case with default header values.

Description was not specified
*/
type GetNutritionLabelJsOK struct {
	Payload string
}

func (o *GetNutritionLabelJsOK) Error() string {
	return fmt.Sprintf("[GET /js/nutritionLabel.js][%d] getNutritionLabelJsOK  %+v", 200, o.Payload)
}

func (o *GetNutritionLabelJsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNutritionLabelJsBadRequest creates a GetNutritionLabelJsBadRequest with default headers values
func NewGetNutritionLabelJsBadRequest() *GetNutritionLabelJsBadRequest {
	return &GetNutritionLabelJsBadRequest{}
}

/*GetNutritionLabelJsBadRequest handles this case with default header values.

Description was not specified
*/
type GetNutritionLabelJsBadRequest struct {
	Payload string
}

func (o *GetNutritionLabelJsBadRequest) Error() string {
	return fmt.Sprintf("[GET /js/nutritionLabel.js][%d] getNutritionLabelJsBadRequest  %+v", 400, o.Payload)
}

func (o *GetNutritionLabelJsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNutritionLabelJsNotFound creates a GetNutritionLabelJsNotFound with default headers values
func NewGetNutritionLabelJsNotFound() *GetNutritionLabelJsNotFound {
	return &GetNutritionLabelJsNotFound{}
}

/*GetNutritionLabelJsNotFound handles this case with default header values.

Description was not specified
*/
type GetNutritionLabelJsNotFound struct {
	Payload string
}

func (o *GetNutritionLabelJsNotFound) Error() string {
	return fmt.Sprintf("[GET /js/nutritionLabel.js][%d] getNutritionLabelJsNotFound  %+v", 404, o.Payload)
}

func (o *GetNutritionLabelJsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
