// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// GetIngredientsForRecipeReader is a Reader for the GetIngredientsForRecipe structure.
type GetIngredientsForRecipeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIngredientsForRecipeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIngredientsForRecipeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetIngredientsForRecipeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetIngredientsForRecipeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIngredientsForRecipeOK creates a GetIngredientsForRecipeOK with default headers values
func NewGetIngredientsForRecipeOK() *GetIngredientsForRecipeOK {
	return &GetIngredientsForRecipeOK{}
}

/*GetIngredientsForRecipeOK handles this case with default header values.

Description was not specified
*/
type GetIngredientsForRecipeOK struct {
	Payload []*models.Ingredient
}

func (o *GetIngredientsForRecipeOK) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient][%d] getIngredientsForRecipeOK  %+v", 200, o.Payload)
}

func (o *GetIngredientsForRecipeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIngredientsForRecipeBadRequest creates a GetIngredientsForRecipeBadRequest with default headers values
func NewGetIngredientsForRecipeBadRequest() *GetIngredientsForRecipeBadRequest {
	return &GetIngredientsForRecipeBadRequest{}
}

/*GetIngredientsForRecipeBadRequest handles this case with default header values.

Description was not specified
*/
type GetIngredientsForRecipeBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *GetIngredientsForRecipeBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient][%d] getIngredientsForRecipeBadRequest  %+v", 400, o.Payload)
}

func (o *GetIngredientsForRecipeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIngredientsForRecipeNotFound creates a GetIngredientsForRecipeNotFound with default headers values
func NewGetIngredientsForRecipeNotFound() *GetIngredientsForRecipeNotFound {
	return &GetIngredientsForRecipeNotFound{}
}

/*GetIngredientsForRecipeNotFound handles this case with default header values.

Description was not specified
*/
type GetIngredientsForRecipeNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *GetIngredientsForRecipeNotFound) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient][%d] getIngredientsForRecipeNotFound  %+v", 404, o.Payload)
}

func (o *GetIngredientsForRecipeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
