// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRecipeIngredientNamesParams creates a new GetRecipeIngredientNamesParams object
// with the default values initialized.
func NewGetRecipeIngredientNamesParams() *GetRecipeIngredientNamesParams {
	var ()
	return &GetRecipeIngredientNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecipeIngredientNamesParamsWithTimeout creates a new GetRecipeIngredientNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRecipeIngredientNamesParamsWithTimeout(timeout time.Duration) *GetRecipeIngredientNamesParams {
	var ()
	return &GetRecipeIngredientNamesParams{

		timeout: timeout,
	}
}

// NewGetRecipeIngredientNamesParamsWithContext creates a new GetRecipeIngredientNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRecipeIngredientNamesParamsWithContext(ctx context.Context) *GetRecipeIngredientNamesParams {
	var ()
	return &GetRecipeIngredientNamesParams{

		Context: ctx,
	}
}

// NewGetRecipeIngredientNamesParamsWithHTTPClient creates a new GetRecipeIngredientNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRecipeIngredientNamesParamsWithHTTPClient(client *http.Client) *GetRecipeIngredientNamesParams {
	var ()
	return &GetRecipeIngredientNamesParams{
		HTTPClient: client,
	}
}

/*GetRecipeIngredientNamesParams contains all the parameters to send to the API endpoint
for the get recipe ingredient names operation typically these are written to a http.Request
*/
type GetRecipeIngredientNamesParams struct {

	/*RecipeID
	  Recipe ID

	*/
	RecipeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) WithTimeout(timeout time.Duration) *GetRecipeIngredientNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) WithContext(ctx context.Context) *GetRecipeIngredientNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) WithHTTPClient(client *http.Client) *GetRecipeIngredientNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecipeID adds the recipeID to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) WithRecipeID(recipeID string) *GetRecipeIngredientNamesParams {
	o.SetRecipeID(recipeID)
	return o
}

// SetRecipeID adds the recipeId to the get recipe ingredient names params
func (o *GetRecipeIngredientNamesParams) SetRecipeID(recipeID string) {
	o.RecipeID = recipeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecipeIngredientNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recipeId
	if err := r.SetPathParam("recipeId", o.RecipeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
