// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNutritionLabelHTMLDynamicSnippetParams creates a new GetNutritionLabelHTMLDynamicSnippetParams object
// with the default values initialized.
func NewGetNutritionLabelHTMLDynamicSnippetParams() *GetNutritionLabelHTMLDynamicSnippetParams {
	var (
		countryDefault = string("uk")
	)
	return &GetNutritionLabelHTMLDynamicSnippetParams{
		Country: &countryDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNutritionLabelHTMLDynamicSnippetParamsWithTimeout creates a new GetNutritionLabelHTMLDynamicSnippetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNutritionLabelHTMLDynamicSnippetParamsWithTimeout(timeout time.Duration) *GetNutritionLabelHTMLDynamicSnippetParams {
	var (
		countryDefault = string("uk")
	)
	return &GetNutritionLabelHTMLDynamicSnippetParams{
		Country: &countryDefault,

		timeout: timeout,
	}
}

// NewGetNutritionLabelHTMLDynamicSnippetParamsWithContext creates a new GetNutritionLabelHTMLDynamicSnippetParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNutritionLabelHTMLDynamicSnippetParamsWithContext(ctx context.Context) *GetNutritionLabelHTMLDynamicSnippetParams {
	var (
		countryDefault = string("uk")
	)
	return &GetNutritionLabelHTMLDynamicSnippetParams{
		Country: &countryDefault,

		Context: ctx,
	}
}

// NewGetNutritionLabelHTMLDynamicSnippetParamsWithHTTPClient creates a new GetNutritionLabelHTMLDynamicSnippetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNutritionLabelHTMLDynamicSnippetParamsWithHTTPClient(client *http.Client) *GetNutritionLabelHTMLDynamicSnippetParams {
	var (
		countryDefault = string("uk")
	)
	return &GetNutritionLabelHTMLDynamicSnippetParams{
		Country:    &countryDefault,
		HTTPClient: client,
	}
}

/*GetNutritionLabelHTMLDynamicSnippetParams contains all the parameters to send to the API endpoint
for the get nutrition label Html dynamic snippet operation typically these are written to a http.Request
*/
type GetNutritionLabelHTMLDynamicSnippetParams struct {

	/*Country
	  The country code which the RDA should reflect.

	*/
	Country *string
	/*PortionSize
	  How large do you want the portions to be? The recipe creators will often decide how many portions a recipe will produce, when following the instructions. However, some people have healthier appetites than others, so this parameter allows control of this element of the recipe. This value is in gramms.

	*/
	PortionSize *int32
	/*Portions
	  The number of portions the parsed ingredients will create.

	*/
	Portions *int32
	/*RecipeID
	  The recipe ID which the nutritional label should be calculated from. This can either be the recipe's integer recipe ID (the primary key) or it's string oid.

	*/
	RecipeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithTimeout(timeout time.Duration) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithContext(ctx context.Context) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithHTTPClient(client *http.Client) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCountry adds the country to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithCountry(country *string) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetCountry(country *string) {
	o.Country = country
}

// WithPortionSize adds the portionSize to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithPortionSize(portionSize *int32) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetPortionSize(portionSize)
	return o
}

// SetPortionSize adds the portionSize to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetPortionSize(portionSize *int32) {
	o.PortionSize = portionSize
}

// WithPortions adds the portions to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithPortions(portions *int32) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetPortions(portions)
	return o
}

// SetPortions adds the portions to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetPortions(portions *int32) {
	o.Portions = portions
}

// WithRecipeID adds the recipeID to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WithRecipeID(recipeID string) *GetNutritionLabelHTMLDynamicSnippetParams {
	o.SetRecipeID(recipeID)
	return o
}

// SetRecipeID adds the recipeId to the get nutrition label Html dynamic snippet params
func (o *GetNutritionLabelHTMLDynamicSnippetParams) SetRecipeID(recipeID string) {
	o.RecipeID = recipeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNutritionLabelHTMLDynamicSnippetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Country != nil {

		// query param country
		var qrCountry string
		if o.Country != nil {
			qrCountry = *o.Country
		}
		qCountry := qrCountry
		if qCountry != "" {
			if err := r.SetQueryParam("country", qCountry); err != nil {
				return err
			}
		}

	}

	if o.PortionSize != nil {

		// query param portionSize
		var qrPortionSize int32
		if o.PortionSize != nil {
			qrPortionSize = *o.PortionSize
		}
		qPortionSize := swag.FormatInt32(qrPortionSize)
		if qPortionSize != "" {
			if err := r.SetQueryParam("portionSize", qPortionSize); err != nil {
				return err
			}
		}

	}

	if o.Portions != nil {

		// query param portions
		var qrPortions int32
		if o.Portions != nil {
			qrPortions = *o.Portions
		}
		qPortions := swag.FormatInt32(qrPortions)
		if qPortions != "" {
			if err := r.SetQueryParam("portions", qPortions); err != nil {
				return err
			}
		}

	}

	// path param recipeId
	if err := r.SetPathParam("recipeId", o.RecipeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
