// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// GetImageQRCodePNGReader is a Reader for the GetImageQRCodePNG structure.
type GetImageQRCodePNGReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageQRCodePNGReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetImageQRCodePNGOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetImageQRCodePNGBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetImageQRCodePNGNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImageQRCodePNGOK creates a GetImageQRCodePNGOK with default headers values
func NewGetImageQRCodePNGOK() *GetImageQRCodePNGOK {
	return &GetImageQRCodePNGOK{}
}

/*GetImageQRCodePNGOK handles this case with default header values.

Here's the image
*/
type GetImageQRCodePNGOK struct {
}

func (o *GetImageQRCodePNGOK) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/qr-image/png][%d] getImageQRCodePNGOK ", 200)
}

func (o *GetImageQRCodePNGOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetImageQRCodePNGBadRequest creates a GetImageQRCodePNGBadRequest with default headers values
func NewGetImageQRCodePNGBadRequest() *GetImageQRCodePNGBadRequest {
	return &GetImageQRCodePNGBadRequest{}
}

/*GetImageQRCodePNGBadRequest handles this case with default header values.

Description was not specified
*/
type GetImageQRCodePNGBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *GetImageQRCodePNGBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/qr-image/png][%d] getImageQRCodePNGBadRequest  %+v", 400, o.Payload)
}

func (o *GetImageQRCodePNGBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageQRCodePNGNotFound creates a GetImageQRCodePNGNotFound with default headers values
func NewGetImageQRCodePNGNotFound() *GetImageQRCodePNGNotFound {
	return &GetImageQRCodePNGNotFound{}
}

/*GetImageQRCodePNGNotFound handles this case with default header values.

Description was not specified
*/
type GetImageQRCodePNGNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *GetImageQRCodePNGNotFound) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/qr-image/png][%d] getImageQRCodePNGNotFound  %+v", 404, o.Payload)
}

func (o *GetImageQRCodePNGNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
