// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCategoriesForRecipeParams creates a new GetCategoriesForRecipeParams object
// with the default values initialized.
func NewGetCategoriesForRecipeParams() *GetCategoriesForRecipeParams {
	var ()
	return &GetCategoriesForRecipeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCategoriesForRecipeParamsWithTimeout creates a new GetCategoriesForRecipeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCategoriesForRecipeParamsWithTimeout(timeout time.Duration) *GetCategoriesForRecipeParams {
	var ()
	return &GetCategoriesForRecipeParams{

		timeout: timeout,
	}
}

// NewGetCategoriesForRecipeParamsWithContext creates a new GetCategoriesForRecipeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCategoriesForRecipeParamsWithContext(ctx context.Context) *GetCategoriesForRecipeParams {
	var ()
	return &GetCategoriesForRecipeParams{

		Context: ctx,
	}
}

// NewGetCategoriesForRecipeParamsWithHTTPClient creates a new GetCategoriesForRecipeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCategoriesForRecipeParamsWithHTTPClient(client *http.Client) *GetCategoriesForRecipeParams {
	var ()
	return &GetCategoriesForRecipeParams{
		HTTPClient: client,
	}
}

/*GetCategoriesForRecipeParams contains all the parameters to send to the API endpoint
for the get categories for recipe operation typically these are written to a http.Request
*/
type GetCategoriesForRecipeParams struct {

	/*RecipeID
	  Recipe ID

	*/
	RecipeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) WithTimeout(timeout time.Duration) *GetCategoriesForRecipeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) WithContext(ctx context.Context) *GetCategoriesForRecipeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) WithHTTPClient(client *http.Client) *GetCategoriesForRecipeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecipeID adds the recipeID to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) WithRecipeID(recipeID string) *GetCategoriesForRecipeParams {
	o.SetRecipeID(recipeID)
	return o
}

// SetRecipeID adds the recipeId to the get categories for recipe params
func (o *GetCategoriesForRecipeParams) SetRecipeID(recipeID string) {
	o.RecipeID = recipeID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCategoriesForRecipeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param recipeId
	if err := r.SetPathParam("recipeId", o.RecipeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
