// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/go-client/models"
)

// GetRecipePNGReader is a Reader for the GetRecipePNG structure.
type GetRecipePNGReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRecipePNGReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRecipePNGOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetRecipePNGBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetRecipePNGNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRecipePNGOK creates a GetRecipePNGOK with default headers values
func NewGetRecipePNGOK() *GetRecipePNGOK {
	return &GetRecipePNGOK{}
}

/*GetRecipePNGOK handles this case with default header values.

The image
*/
type GetRecipePNGOK struct {
}

func (o *GetRecipePNGOK) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/image][%d] getRecipePNGOK ", 200)
}

func (o *GetRecipePNGOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRecipePNGBadRequest creates a GetRecipePNGBadRequest with default headers values
func NewGetRecipePNGBadRequest() *GetRecipePNGBadRequest {
	return &GetRecipePNGBadRequest{}
}

/*GetRecipePNGBadRequest handles this case with default header values.

Description was not specified
*/
type GetRecipePNGBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *GetRecipePNGBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/image][%d] getRecipePNGBadRequest  %+v", 400, o.Payload)
}

func (o *GetRecipePNGBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRecipePNGNotFound creates a GetRecipePNGNotFound with default headers values
func NewGetRecipePNGNotFound() *GetRecipePNGNotFound {
	return &GetRecipePNGNotFound{}
}

/*GetRecipePNGNotFound handles this case with default header values.

Description was not specified
*/
type GetRecipePNGNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *GetRecipePNGNotFound) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/image][%d] getRecipePNGNotFound  %+v", 404, o.Payload)
}

func (o *GetRecipePNGNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
