// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// ListIngredientsWithNutritionReader is a Reader for the ListIngredientsWithNutrition structure.
type ListIngredientsWithNutritionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIngredientsWithNutritionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListIngredientsWithNutritionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewListIngredientsWithNutritionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewListIngredientsWithNutritionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListIngredientsWithNutritionOK creates a ListIngredientsWithNutritionOK with default headers values
func NewListIngredientsWithNutritionOK() *ListIngredientsWithNutritionOK {
	return &ListIngredientsWithNutritionOK{}
}

/*ListIngredientsWithNutritionOK handles this case with default header values.

Description was not specified
*/
type ListIngredientsWithNutritionOK struct {
	Payload []*models.IngredientWithNutritionAbbrev
}

func (o *ListIngredientsWithNutritionOK) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient/nutrition][%d] listIngredientsWithNutritionOK  %+v", 200, o.Payload)
}

func (o *ListIngredientsWithNutritionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIngredientsWithNutritionBadRequest creates a ListIngredientsWithNutritionBadRequest with default headers values
func NewListIngredientsWithNutritionBadRequest() *ListIngredientsWithNutritionBadRequest {
	return &ListIngredientsWithNutritionBadRequest{}
}

/*ListIngredientsWithNutritionBadRequest handles this case with default header values.

Description was not specified
*/
type ListIngredientsWithNutritionBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *ListIngredientsWithNutritionBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient/nutrition][%d] listIngredientsWithNutritionBadRequest  %+v", 400, o.Payload)
}

func (o *ListIngredientsWithNutritionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIngredientsWithNutritionNotFound creates a ListIngredientsWithNutritionNotFound with default headers values
func NewListIngredientsWithNutritionNotFound() *ListIngredientsWithNutritionNotFound {
	return &ListIngredientsWithNutritionNotFound{}
}

/*ListIngredientsWithNutritionNotFound handles this case with default header values.

Description was not specified
*/
type ListIngredientsWithNutritionNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *ListIngredientsWithNutritionNotFound) Error() string {
	return fmt.Sprintf("[GET /recipe/{recipeId}/ingredient/nutrition][%d] listIngredientsWithNutritionNotFound  %+v", 404, o.Payload)
}

func (o *ListIngredientsWithNutritionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
