// Code generated by go-swagger; DO NOT EDIT.

package recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// PagedSearchRecipesReader is a Reader for the PagedSearchRecipes structure.
type PagedSearchRecipesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PagedSearchRecipesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPagedSearchRecipesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPagedSearchRecipesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPagedSearchRecipesOK creates a PagedSearchRecipesOK with default headers values
func NewPagedSearchRecipesOK() *PagedSearchRecipesOK {
	return &PagedSearchRecipesOK{}
}

/*PagedSearchRecipesOK handles this case with default header values.

Description was not specified
*/
type PagedSearchRecipesOK struct {
	Payload *models.PagedRecipeResults
}

func (o *PagedSearchRecipesOK) Error() string {
	return fmt.Sprintf("[GET /recipe/search][%d] pagedSearchRecipesOK  %+v", 200, o.Payload)
}

func (o *PagedSearchRecipesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedRecipeResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPagedSearchRecipesBadRequest creates a PagedSearchRecipesBadRequest with default headers values
func NewPagedSearchRecipesBadRequest() *PagedSearchRecipesBadRequest {
	return &PagedSearchRecipesBadRequest{}
}

/*PagedSearchRecipesBadRequest handles this case with default header values.

Description was not specified
*/
type PagedSearchRecipesBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *PagedSearchRecipesBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe/search][%d] pagedSearchRecipesBadRequest  %+v", 400, o.Payload)
}

func (o *PagedSearchRecipesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
