// Code generated by go-swagger; DO NOT EDIT.

package scratch_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// DeleteScratchPadRecipeReader is a Reader for the DeleteScratchPadRecipe structure.
type DeleteScratchPadRecipeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteScratchPadRecipeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteScratchPadRecipeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteScratchPadRecipeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteScratchPadRecipeOK creates a DeleteScratchPadRecipeOK with default headers values
func NewDeleteScratchPadRecipeOK() *DeleteScratchPadRecipeOK {
	return &DeleteScratchPadRecipeOK{}
}

/*DeleteScratchPadRecipeOK handles this case with default header values.

Description was not specified
*/
type DeleteScratchPadRecipeOK struct {
	Payload *models.HTTPAPIResponse
}

func (o *DeleteScratchPadRecipeOK) Error() string {
	return fmt.Sprintf("[DELETE /scratch-recipe/{recipeId}][%d] deleteScratchPadRecipeOK  %+v", 200, o.Payload)
}

func (o *DeleteScratchPadRecipeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteScratchPadRecipeBadRequest creates a DeleteScratchPadRecipeBadRequest with default headers values
func NewDeleteScratchPadRecipeBadRequest() *DeleteScratchPadRecipeBadRequest {
	return &DeleteScratchPadRecipeBadRequest{}
}

/*DeleteScratchPadRecipeBadRequest handles this case with default header values.

Malformed JSON (this endpoint requires an array of strings
*/
type DeleteScratchPadRecipeBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *DeleteScratchPadRecipeBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scratch-recipe/{recipeId}][%d] deleteScratchPadRecipeBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteScratchPadRecipeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
