// Code generated by go-swagger; DO NOT EDIT.

package scratch_recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// GetAllMyScratchRecipesReader is a Reader for the GetAllMyScratchRecipes structure.
type GetAllMyScratchRecipesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllMyScratchRecipesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllMyScratchRecipesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAllMyScratchRecipesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAllMyScratchRecipesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllMyScratchRecipesOK creates a GetAllMyScratchRecipesOK with default headers values
func NewGetAllMyScratchRecipesOK() *GetAllMyScratchRecipesOK {
	return &GetAllMyScratchRecipesOK{}
}

/*GetAllMyScratchRecipesOK handles this case with default header values.

Retreives a list of the currenty logged in user's scratch pad
*/
type GetAllMyScratchRecipesOK struct {
	Payload []*models.Recipe
}

func (o *GetAllMyScratchRecipesOK) Error() string {
	return fmt.Sprintf("[GET /scratch-recipe][%d] getAllMyScratchRecipesOK  %+v", 200, o.Payload)
}

func (o *GetAllMyScratchRecipesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllMyScratchRecipesBadRequest creates a GetAllMyScratchRecipesBadRequest with default headers values
func NewGetAllMyScratchRecipesBadRequest() *GetAllMyScratchRecipesBadRequest {
	return &GetAllMyScratchRecipesBadRequest{}
}

/*GetAllMyScratchRecipesBadRequest handles this case with default header values.

Malformed JSON (this endpoint requires an array of strings
*/
type GetAllMyScratchRecipesBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *GetAllMyScratchRecipesBadRequest) Error() string {
	return fmt.Sprintf("[GET /scratch-recipe][%d] getAllMyScratchRecipesBadRequest  %+v", 400, o.Payload)
}

func (o *GetAllMyScratchRecipesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllMyScratchRecipesForbidden creates a GetAllMyScratchRecipesForbidden with default headers values
func NewGetAllMyScratchRecipesForbidden() *GetAllMyScratchRecipesForbidden {
	return &GetAllMyScratchRecipesForbidden{}
}

/*GetAllMyScratchRecipesForbidden handles this case with default header values.

Description was not specified
*/
type GetAllMyScratchRecipesForbidden struct {
	Payload *models.HTTPAPIError
}

func (o *GetAllMyScratchRecipesForbidden) Error() string {
	return fmt.Sprintf("[GET /scratch-recipe][%d] getAllMyScratchRecipesForbidden  %+v", 403, o.Payload)
}

func (o *GetAllMyScratchRecipesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
