// Code generated by go-swagger; DO NOT EDIT.

package recipe_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// NewPutMenuItemParams creates a new PutMenuItemParams object
// with the default values initialized.
func NewPutMenuItemParams() *PutMenuItemParams {
	var ()
	return &PutMenuItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMenuItemParamsWithTimeout creates a new PutMenuItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMenuItemParamsWithTimeout(timeout time.Duration) *PutMenuItemParams {
	var ()
	return &PutMenuItemParams{

		timeout: timeout,
	}
}

// NewPutMenuItemParamsWithContext creates a new PutMenuItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMenuItemParamsWithContext(ctx context.Context) *PutMenuItemParams {
	var ()
	return &PutMenuItemParams{

		Context: ctx,
	}
}

// NewPutMenuItemParamsWithHTTPClient creates a new PutMenuItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMenuItemParamsWithHTTPClient(client *http.Client) *PutMenuItemParams {
	var ()
	return &PutMenuItemParams{
		HTTPClient: client,
	}
}

/*PutMenuItemParams contains all the parameters to send to the API endpoint
for the put menu item operation typically these are written to a http.Request
*/
type PutMenuItemParams struct {

	/*JSONBody
	  The menu item data to be changed.

	*/
	JSONBody *models.MenuItem
	/*MenuItemID
	  The menu item ID of the item you want to change.

	*/
	MenuItemID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put menu item params
func (o *PutMenuItemParams) WithTimeout(timeout time.Duration) *PutMenuItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put menu item params
func (o *PutMenuItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put menu item params
func (o *PutMenuItemParams) WithContext(ctx context.Context) *PutMenuItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put menu item params
func (o *PutMenuItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put menu item params
func (o *PutMenuItemParams) WithHTTPClient(client *http.Client) *PutMenuItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put menu item params
func (o *PutMenuItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the put menu item params
func (o *PutMenuItemParams) WithJSONBody(jSONBody *models.MenuItem) *PutMenuItemParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the put menu item params
func (o *PutMenuItemParams) SetJSONBody(jSONBody *models.MenuItem) {
	o.JSONBody = jSONBody
}

// WithMenuItemID adds the menuItemID to the put menu item params
func (o *PutMenuItemParams) WithMenuItemID(menuItemID int64) *PutMenuItemParams {
	o.SetMenuItemID(menuItemID)
	return o
}

// SetMenuItemID adds the menuItemId to the put menu item params
func (o *PutMenuItemParams) SetMenuItemID(menuItemID int64) {
	o.MenuItemID = menuItemID
}

// WriteToRequest writes these params to a swagger request
func (o *PutMenuItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	// path param menuItemId
	if err := r.SetPathParam("menuItemId", swag.FormatInt64(o.MenuItemID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
