// Code generated by go-swagger; DO NOT EDIT.

package recipe_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/go-client/models"
)

// SearchMyRecipeGroupForRecipeReader is a Reader for the SearchMyRecipeGroupForRecipe structure.
type SearchMyRecipeGroupForRecipeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchMyRecipeGroupForRecipeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchMyRecipeGroupForRecipeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchMyRecipeGroupForRecipeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchMyRecipeGroupForRecipeOK creates a SearchMyRecipeGroupForRecipeOK with default headers values
func NewSearchMyRecipeGroupForRecipeOK() *SearchMyRecipeGroupForRecipeOK {
	return &SearchMyRecipeGroupForRecipeOK{}
}

/*SearchMyRecipeGroupForRecipeOK handles this case with default header values.

Description was not specified
*/
type SearchMyRecipeGroupForRecipeOK struct {
	Payload []*models.RecipeGroup
}

func (o *SearchMyRecipeGroupForRecipeOK) Error() string {
	return fmt.Sprintf("[GET /recipe-group/my-recipes/{recipeId}][%d] searchMyRecipeGroupForRecipeOK  %+v", 200, o.Payload)
}

func (o *SearchMyRecipeGroupForRecipeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchMyRecipeGroupForRecipeBadRequest creates a SearchMyRecipeGroupForRecipeBadRequest with default headers values
func NewSearchMyRecipeGroupForRecipeBadRequest() *SearchMyRecipeGroupForRecipeBadRequest {
	return &SearchMyRecipeGroupForRecipeBadRequest{}
}

/*SearchMyRecipeGroupForRecipeBadRequest handles this case with default header values.

Description was not specified
*/
type SearchMyRecipeGroupForRecipeBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *SearchMyRecipeGroupForRecipeBadRequest) Error() string {
	return fmt.Sprintf("[GET /recipe-group/my-recipes/{recipeId}][%d] searchMyRecipeGroupForRecipeBadRequest  %+v", 400, o.Payload)
}

func (o *SearchMyRecipeGroupForRecipeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
