// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/go-client/models"
)

// AccountSigninReader is a Reader for the AccountSignin structure.
type AccountSigninReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountSigninReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAccountSigninOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAccountSigninBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAccountSigninOK creates a AccountSigninOK with default headers values
func NewAccountSigninOK() *AccountSigninOK {
	return &AccountSigninOK{}
}

/*AccountSigninOK handles this case with default header values.

Description was not specified
*/
type AccountSigninOK struct {
	Payload *models.User
}

func (o *AccountSigninOK) Error() string {
	return fmt.Sprintf("[POST /signin][%d] accountSigninOK  %+v", 200, o.Payload)
}

func (o *AccountSigninOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountSigninBadRequest creates a AccountSigninBadRequest with default headers values
func NewAccountSigninBadRequest() *AccountSigninBadRequest {
	return &AccountSigninBadRequest{}
}

/*AccountSigninBadRequest handles this case with default header values.

Description was not specified
*/
type AccountSigninBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *AccountSigninBadRequest) Error() string {
	return fmt.Sprintf("[POST /signin][%d] accountSigninBadRequest  %+v", 400, o.Payload)
}

func (o *AccountSigninBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
