// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// NewFacebookSignupSigninParams creates a new FacebookSignupSigninParams object
// with the default values initialized.
func NewFacebookSignupSigninParams() *FacebookSignupSigninParams {
	var ()
	return &FacebookSignupSigninParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFacebookSignupSigninParamsWithTimeout creates a new FacebookSignupSigninParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFacebookSignupSigninParamsWithTimeout(timeout time.Duration) *FacebookSignupSigninParams {
	var ()
	return &FacebookSignupSigninParams{

		timeout: timeout,
	}
}

// NewFacebookSignupSigninParamsWithContext creates a new FacebookSignupSigninParams object
// with the default values initialized, and the ability to set a context for a request
func NewFacebookSignupSigninParamsWithContext(ctx context.Context) *FacebookSignupSigninParams {
	var ()
	return &FacebookSignupSigninParams{

		Context: ctx,
	}
}

// NewFacebookSignupSigninParamsWithHTTPClient creates a new FacebookSignupSigninParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFacebookSignupSigninParamsWithHTTPClient(client *http.Client) *FacebookSignupSigninParams {
	var ()
	return &FacebookSignupSigninParams{
		HTTPClient: client,
	}
}

/*FacebookSignupSigninParams contains all the parameters to send to the API endpoint
for the facebook signup signin operation typically these are written to a http.Request
*/
type FacebookSignupSigninParams struct {

	/*JSONBody
	  A valid facebook access token which will be used to sign the user up.

	*/
	JSONBody *models.FacebookSigninObject

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the facebook signup signin params
func (o *FacebookSignupSigninParams) WithTimeout(timeout time.Duration) *FacebookSignupSigninParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the facebook signup signin params
func (o *FacebookSignupSigninParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the facebook signup signin params
func (o *FacebookSignupSigninParams) WithContext(ctx context.Context) *FacebookSignupSigninParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the facebook signup signin params
func (o *FacebookSignupSigninParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the facebook signup signin params
func (o *FacebookSignupSigninParams) WithHTTPClient(client *http.Client) *FacebookSignupSigninParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the facebook signup signin params
func (o *FacebookSignupSigninParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the facebook signup signin params
func (o *FacebookSignupSigninParams) WithJSONBody(jSONBody *models.FacebookSigninObject) *FacebookSignupSigninParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the facebook signup signin params
func (o *FacebookSignupSigninParams) SetJSONBody(jSONBody *models.FacebookSigninObject) {
	o.JSONBody = jSONBody
}

// WriteToRequest writes these params to a swagger request
func (o *FacebookSignupSigninParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
