// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// SaveUserReader is a Reader for the SaveUser structure.
type SaveUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSaveUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewSaveUserCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSaveUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSaveUserOK creates a SaveUserOK with default headers values
func NewSaveUserOK() *SaveUserOK {
	return &SaveUserOK{}
}

/*SaveUserOK handles this case with default header values.

No response was specified
*/
type SaveUserOK struct {
	Payload *models.User
}

func (o *SaveUserOK) Error() string {
	return fmt.Sprintf("[POST /fb_signup][%d] saveUserOK  %+v", 200, o.Payload)
}

func (o *SaveUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveUserCreated creates a SaveUserCreated with default headers values
func NewSaveUserCreated() *SaveUserCreated {
	return &SaveUserCreated{}
}

/*SaveUserCreated handles this case with default header values.

Description was not specified
*/
type SaveUserCreated struct {
	Payload *models.User
}

func (o *SaveUserCreated) Error() string {
	return fmt.Sprintf("[POST /fb_signup][%d] saveUserCreated  %+v", 201, o.Payload)
}

func (o *SaveUserCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveUserBadRequest creates a SaveUserBadRequest with default headers values
func NewSaveUserBadRequest() *SaveUserBadRequest {
	return &SaveUserBadRequest{}
}

/*SaveUserBadRequest handles this case with default header values.

Description was not specified
*/
type SaveUserBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *SaveUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /fb_signup][%d] saveUserBadRequest  %+v", 400, o.Payload)
}

func (o *SaveUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
