// Code generated by go-swagger; DO NOT EDIT.

package nutrition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// ShowNutritionForAFoodReader is a Reader for the ShowNutritionForAFood structure.
type ShowNutritionForAFoodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowNutritionForAFoodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewShowNutritionForAFoodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewShowNutritionForAFoodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewShowNutritionForAFoodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewShowNutritionForAFoodOK creates a ShowNutritionForAFoodOK with default headers values
func NewShowNutritionForAFoodOK() *ShowNutritionForAFoodOK {
	return &ShowNutritionForAFoodOK{}
}

/*ShowNutritionForAFoodOK handles this case with default header values.

Description was not specified
*/
type ShowNutritionForAFoodOK struct {
	Payload *models.NutritionAbbrev
}

func (o *ShowNutritionForAFoodOK) Error() string {
	return fmt.Sprintf("[GET /food-nutrition/food/{foodId}/{amount}][%d] showNutritionForAFoodOK  %+v", 200, o.Payload)
}

func (o *ShowNutritionForAFoodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NutritionAbbrev)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowNutritionForAFoodBadRequest creates a ShowNutritionForAFoodBadRequest with default headers values
func NewShowNutritionForAFoodBadRequest() *ShowNutritionForAFoodBadRequest {
	return &ShowNutritionForAFoodBadRequest{}
}

/*ShowNutritionForAFoodBadRequest handles this case with default header values.

Description was not specified
*/
type ShowNutritionForAFoodBadRequest struct {
	Payload *models.HTTPAPIError
}

func (o *ShowNutritionForAFoodBadRequest) Error() string {
	return fmt.Sprintf("[GET /food-nutrition/food/{foodId}/{amount}][%d] showNutritionForAFoodBadRequest  %+v", 400, o.Payload)
}

func (o *ShowNutritionForAFoodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowNutritionForAFoodNotFound creates a ShowNutritionForAFoodNotFound with default headers values
func NewShowNutritionForAFoodNotFound() *ShowNutritionForAFoodNotFound {
	return &ShowNutritionForAFoodNotFound{}
}

/*ShowNutritionForAFoodNotFound handles this case with default header values.

Description was not specified
*/
type ShowNutritionForAFoodNotFound struct {
	Payload *models.HTTPAPIError
}

func (o *ShowNutritionForAFoodNotFound) Error() string {
	return fmt.Sprintf("[GET /food-nutrition/food/{foodId}/{amount}][%d] showNutritionForAFoodNotFound  %+v", 404, o.Payload)
}

func (o *ShowNutritionForAFoodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
