// Code generated by go-swagger; DO NOT EDIT.

package parse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IncorrectIngredientParsingReader is a Reader for the IncorrectIngredientParsing structure.
type IncorrectIngredientParsingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IncorrectIngredientParsingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIncorrectIngredientParsingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIncorrectIngredientParsingOK creates a IncorrectIngredientParsingOK with default headers values
func NewIncorrectIngredientParsingOK() *IncorrectIngredientParsingOK {
	return &IncorrectIngredientParsingOK{}
}

/*IncorrectIngredientParsingOK handles this case with default header values.

Notification received
*/
type IncorrectIngredientParsingOK struct {
}

func (o *IncorrectIngredientParsingOK) Error() string {
	return fmt.Sprintf("[GET /parse/notify-error/{parsedId}][%d] incorrectIngredientParsingOK ", 200)
}

func (o *IncorrectIngredientParsingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
