// Code generated by go-swagger; DO NOT EDIT.

package parse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/go-client/models"
)

// NewParseRecipeByURLPostParams creates a new ParseRecipeByURLPostParams object
// with the default values initialized.
func NewParseRecipeByURLPostParams() *ParseRecipeByURLPostParams {
	var ()
	return &ParseRecipeByURLPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewParseRecipeByURLPostParamsWithTimeout creates a new ParseRecipeByURLPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewParseRecipeByURLPostParamsWithTimeout(timeout time.Duration) *ParseRecipeByURLPostParams {
	var ()
	return &ParseRecipeByURLPostParams{

		timeout: timeout,
	}
}

// NewParseRecipeByURLPostParamsWithContext creates a new ParseRecipeByURLPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewParseRecipeByURLPostParamsWithContext(ctx context.Context) *ParseRecipeByURLPostParams {
	var ()
	return &ParseRecipeByURLPostParams{

		Context: ctx,
	}
}

// NewParseRecipeByURLPostParamsWithHTTPClient creates a new ParseRecipeByURLPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewParseRecipeByURLPostParamsWithHTTPClient(client *http.Client) *ParseRecipeByURLPostParams {
	var ()
	return &ParseRecipeByURLPostParams{
		HTTPClient: client,
	}
}

/*ParseRecipeByURLPostParams contains all the parameters to send to the API endpoint
for the parse recipe by Url post operation typically these are written to a http.Request
*/
type ParseRecipeByURLPostParams struct {

	/*JSONBody
	  A url to a recipe, which a sous bot will download and attempt, as best it can to parse into a recipe object and a list of ingredients.

	*/
	JSONBody *models.PlainString

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) WithTimeout(timeout time.Duration) *ParseRecipeByURLPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) WithContext(ctx context.Context) *ParseRecipeByURLPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) WithHTTPClient(client *http.Client) *ParseRecipeByURLPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) WithJSONBody(jSONBody *models.PlainString) *ParseRecipeByURLPostParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the parse recipe by Url post params
func (o *ParseRecipeByURLPostParams) SetJSONBody(jSONBody *models.PlainString) {
	o.JSONBody = jSONBody
}

// WriteToRequest writes these params to a swagger request
func (o *ParseRecipeByURLPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
