// Code generated by go-swagger; DO NOT EDIT.

package parse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cheerychow/chow-go-client/models"
)

// NewParseRecipeViaPageContentParams creates a new ParseRecipeViaPageContentParams object
// with the default values initialized.
func NewParseRecipeViaPageContentParams() *ParseRecipeViaPageContentParams {
	var ()
	return &ParseRecipeViaPageContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewParseRecipeViaPageContentParamsWithTimeout creates a new ParseRecipeViaPageContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewParseRecipeViaPageContentParamsWithTimeout(timeout time.Duration) *ParseRecipeViaPageContentParams {
	var ()
	return &ParseRecipeViaPageContentParams{

		timeout: timeout,
	}
}

// NewParseRecipeViaPageContentParamsWithContext creates a new ParseRecipeViaPageContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewParseRecipeViaPageContentParamsWithContext(ctx context.Context) *ParseRecipeViaPageContentParams {
	var ()
	return &ParseRecipeViaPageContentParams{

		Context: ctx,
	}
}

// NewParseRecipeViaPageContentParamsWithHTTPClient creates a new ParseRecipeViaPageContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewParseRecipeViaPageContentParamsWithHTTPClient(client *http.Client) *ParseRecipeViaPageContentParams {
	var ()
	return &ParseRecipeViaPageContentParams{
		HTTPClient: client,
	}
}

/*ParseRecipeViaPageContentParams contains all the parameters to send to the API endpoint
for the parse recipe via page content operation typically these are written to a http.Request
*/
type ParseRecipeViaPageContentParams struct {

	/*JSONBody
	  An object describing a recipe to be parsed into seperate ingredients.

	*/
	JSONBody *models.RecipeParseRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) WithTimeout(timeout time.Duration) *ParseRecipeViaPageContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) WithContext(ctx context.Context) *ParseRecipeViaPageContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) WithHTTPClient(client *http.Client) *ParseRecipeViaPageContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJSONBody adds the jSONBody to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) WithJSONBody(jSONBody *models.RecipeParseRequest) *ParseRecipeViaPageContentParams {
	o.SetJSONBody(jSONBody)
	return o
}

// SetJSONBody adds the jsonBody to the parse recipe via page content params
func (o *ParseRecipeViaPageContentParams) SetJSONBody(jSONBody *models.RecipeParseRequest) {
	o.JSONBody = jSONBody
}

// WriteToRequest writes these params to a swagger request
func (o *ParseRecipeViaPageContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JSONBody != nil {
		if err := r.SetBodyParam(o.JSONBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
