// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AuthProvider auth provider
// swagger:model AuthProvider
type AuthProvider struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// provider id
	ProviderID string `json:"provider_id,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this auth provider
func (m *AuthProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthProvider) UnmarshalBinary(b []byte) error {
	var res AuthProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
