// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FoodDes food des
// swagger:model FoodDes
type FoodDes struct {

	// category
	Category string `json:"category,omitempty"`

	// cho factor
	ChoFactor float32 `json:"cho_factor,omitempty"`

	// common name
	CommonName string `json:"common_name,omitempty"`

	// fat factor
	FatFactor float32 `json:"fat_factor,omitempty"`

	// food id
	FoodID int64 `json:"food_id,omitempty"`

	// manufacturer
	Manufacturer string `json:"manufacturer,omitempty"`

	// n factor
	NFactor float32 `json:"n_factor,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pro factor
	ProFactor float32 `json:"pro_factor,omitempty"`

	// ref desc
	RefDesc string `json:"ref_desc,omitempty"`

	// refuse
	Refuse int32 `json:"refuse,omitempty"`

	// sciname
	Sciname string `json:"sciname,omitempty"`

	// shrt desc
	ShrtDesc string `json:"shrt_desc,omitempty"`

	// survey
	Survey string `json:"survey,omitempty"`
}

// Validate validates this food des
func (m *FoodDes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FoodDes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FoodDes) UnmarshalBinary(b []byte) error {
	var res FoodDes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
