// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FoodWithID food with ID
// swagger:model FoodWithID
type FoodWithID struct {

	// food id
	FoodID int64 `json:"food_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this food with ID
func (m *FoodWithID) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FoodWithID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FoodWithID) UnmarshalBinary(b []byte) error {
	var res FoodWithID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
