// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IngredientOp ingredient op
// swagger:model IngredientOp
type IngredientOp struct {
	Ingredient

	IngOp
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *IngredientOp) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Ingredient
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Ingredient = aO0

	// AO1
	var aO1 IngOp
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.IngOp = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m IngredientOp) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Ingredient)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.IngOp)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this ingredient op
func (m *IngredientOp) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Ingredient
	if err := m.Ingredient.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with IngOp
	if err := m.IngOp.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IngredientOp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IngredientOp) UnmarshalBinary(b []byte) error {
	var res IngredientOp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
