// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NutritionAbbrev nutrition abbrev
// swagger:model NutritionAbbrev
type NutritionAbbrev struct {
	BaseNutritionAbbrev

	// nut food id
	NutFoodID int64 `json:"nut_food_id,omitempty"`

	// shrt desc
	ShrtDesc string `json:"shrt_desc,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *NutritionAbbrev) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseNutritionAbbrev
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BaseNutritionAbbrev = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m NutritionAbbrev) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.BaseNutritionAbbrev)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this nutrition abbrev
func (m *NutritionAbbrev) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseNutritionAbbrev
	if err := m.BaseNutritionAbbrev.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NutritionAbbrev) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NutritionAbbrev) UnmarshalBinary(b []byte) error {
	var res NutritionAbbrev
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
