// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NutrDef nutr def
// swagger:model NutrDef
type NutrDef struct {

	// name
	Name string `json:"name,omitempty"`

	// nutrient id
	NutrientID string `json:"nutrient_id,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`

	// units
	Units string `json:"units,omitempty"`
}

// Validate validates this nutr def
func (m *NutrDef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NutrDef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NutrDef) UnmarshalBinary(b []byte) error {
	var res NutrDef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
