// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NutritionTip nutrition tip
// swagger:model NutritionTip
type NutritionTip struct {

	// Each food abilty is a general category nutrients provide benefits for, e.g. youthful consider nutrients which help with skin and hair.
	AbilityID int64 `json:"ability_id,omitempty"`

	// nutrient id
	NutrientID int64 `json:"nutrient_id,omitempty"`

	// nutrient key
	NutrientKey string `json:"nutrient_key,omitempty"`

	// nutrient name
	NutrientName string `json:"nutrient_name,omitempty"`

	// The 'tip' text.
	Tip []string `json:"tip"`

	// tip category
	TipCategory string `json:"tip_category,omitempty"`

	// tip id
	TipID int64 `json:"tip_id,omitempty"`

	// How applicable (i.e. how much does ) is this tip. This is a subjective value and takes into account papers puplished for and against the 'tip' in the context of the nutrient.
	Weight int64 `json:"weight,omitempty"`
}

// Validate validates this nutrition tip
func (m *NutritionTip) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NutritionTip) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NutritionTip) UnmarshalBinary(b []byte) error {
	var res NutritionTip
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
