// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NutritionInfo nutrition info
// swagger:model NutritionInfo
type NutritionInfo struct {

	// Id
	ID int64 `json:"Id,omitempty"`

	// benefits
	Benefits string `json:"benefits,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// nutrient id
	NutrientID int64 `json:"nutrient_id,omitempty"`

	// nutrient name
	NutrientName string `json:"nutrient_name,omitempty"`

	// what is
	WhatIs string `json:"what_is,omitempty"`
}

// Validate validates this nutrition info
func (m *NutritionInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NutritionInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NutritionInfo) UnmarshalBinary(b []byte) error {
	var res NutritionInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
