// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PopularIngredients popular ingredients
// swagger:model PopularIngredients
type PopularIngredients struct {

	// common name
	CommonName string `json:"common_name,omitempty"`

	// food group id
	FoodGroupID int64 `json:"food_group_id,omitempty"`

	// food id
	FoodID int64 `json:"food_id,omitempty"`

	// occurrences
	Occurrences int32 `json:"occurrences,omitempty"`
}

// Validate validates this popular ingredients
func (m *PopularIngredients) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PopularIngredients) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PopularIngredients) UnmarshalBinary(b []byte) error {
	var res PopularIngredients
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
