// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserStats user stats
// swagger:model UserStats
type UserStats struct {

	// handle
	Handle string `json:"handle,omitempty"`

	// num followers
	NumFollowers int32 `json:"num_followers,omitempty"`

	// num recipes
	NumRecipes int32 `json:"num_recipes,omitempty"`

	// num restaurants
	NumRestaurants int32 `json:"num_restaurants,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this user stats
func (m *UserStats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserStats) UnmarshalBinary(b []byte) error {
	var res UserStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
