// Code generated by go-swagger; DO NOT EDIT.

package labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNutrientAbbrevsParams creates a new NutrientAbbrevsParams object
// with the default values initialized.
func NewNutrientAbbrevsParams() *NutrientAbbrevsParams {

	return &NutrientAbbrevsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNutrientAbbrevsParamsWithTimeout creates a new NutrientAbbrevsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNutrientAbbrevsParamsWithTimeout(timeout time.Duration) *NutrientAbbrevsParams {

	return &NutrientAbbrevsParams{

		timeout: timeout,
	}
}

// NewNutrientAbbrevsParamsWithContext creates a new NutrientAbbrevsParams object
// with the default values initialized, and the ability to set a context for a request
func NewNutrientAbbrevsParamsWithContext(ctx context.Context) *NutrientAbbrevsParams {

	return &NutrientAbbrevsParams{

		Context: ctx,
	}
}

// NewNutrientAbbrevsParamsWithHTTPClient creates a new NutrientAbbrevsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNutrientAbbrevsParamsWithHTTPClient(client *http.Client) *NutrientAbbrevsParams {

	return &NutrientAbbrevsParams{
		HTTPClient: client,
	}
}

/*NutrientAbbrevsParams contains all the parameters to send to the API endpoint
for the nutrient abbrevs operation typically these are written to a http.Request
*/
type NutrientAbbrevsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) WithTimeout(timeout time.Duration) *NutrientAbbrevsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) WithContext(ctx context.Context) *NutrientAbbrevsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) WithHTTPClient(client *http.Client) *NutrientAbbrevsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nutrient abbrevs params
func (o *NutrientAbbrevsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *NutrientAbbrevsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
